namespace WebCV.Infrastructure.Services
{
    public class ClaudeService(HttpClient httpClient, string apiKey) : IAIService
    {
        private readonly HttpClient _httpClient = httpClient;
        private readonly string _apiKey = apiKey;
        private const string ApiUrl = "https://api.anthropic.com/v1/messages";
        private const string Model = "claude-3-5-haiku-20241022";
        private const string ApiVersion = "2023-06-01";

        public async Task<string> GenerateCoverLetterAsync(CandidateProfile profile, JobPosting job)
        {
            string prompt = $"{AISystemPrompts.CoverLetterSystemPrompt}\n\n{BuildPrompt(profile, job)}";
            
            var requestPayload = new
            {
                model = Model,
                max_tokens = 4096,
                system = AISystemPrompts.CoverLetterSystemPrompt,
                messages = new[]
                {
                    new { role = "user", content = BuildPrompt(profile, job) }
                }
            };

            var jsonPayload = JsonSerializer.Serialize(requestPayload);
            var content = new StringContent(jsonPayload, Encoding.UTF8, "application/json");

            _httpClient.DefaultRequestHeaders.Clear();
            _httpClient.DefaultRequestHeaders.Add("x-api-key", _apiKey);
            _httpClient.DefaultRequestHeaders.Add("anthropic-version", ApiVersion);

            var response = await _httpClient.PostAsync(ApiUrl, content);

            if (!response.IsSuccessStatusCode)
            {
                var error = await response.Content.ReadAsStringAsync();
                throw new Exception($"Claude API Error: {response.StatusCode} - {error}");
            }

            var responseJson = await response.Content.ReadAsStringAsync();
            var claudeResponse = JsonSerializer.Deserialize<ClaudeResponse>(responseJson);

            return claudeResponse?.Content?[0]?.Text 
                ?? "Error: No content generated.";
        }

        public async Task<TailoredResumeResult> GenerateTailoredResumeAsync(CandidateProfile profile, JobPosting job)
        {
            var prompt = $"{AISystemPrompts.ResumeTailoringSystemPrompt}\n\n{BuildPrompt(profile, job, isResume: true)}";
            
            var requestPayload = new
            {
                model = Model,
                max_tokens = 4096,
                system = AISystemPrompts.ResumeTailoringSystemPrompt,
                messages = new[]
                {
                    new { role = "user", content = BuildPrompt(profile, job, isResume: true) }
                }
            };

            var jsonPayload = JsonSerializer.Serialize(requestPayload);
            var content = new StringContent(jsonPayload, Encoding.UTF8, "application/json");

            _httpClient.DefaultRequestHeaders.Clear();
            _httpClient.DefaultRequestHeaders.Add("x-api-key", _apiKey);
            _httpClient.DefaultRequestHeaders.Add("anthropic-version", ApiVersion);

            var response = await _httpClient.PostAsync(ApiUrl, content);

            if (!response.IsSuccessStatusCode)
            {
                var error = await response.Content.ReadAsStringAsync();
                throw new Exception($"Claude API Error: {response.StatusCode} - {error}");
            }

            var responseJson = await response.Content.ReadAsStringAsync();
            var claudeResponse = JsonSerializer.Deserialize<ClaudeResponse>(responseJson);
            var textResponse = claudeResponse?.Content?[0]?.Text;

            if (string.IsNullOrEmpty(textResponse))
            {
                throw new Exception("No content generated by Claude.");
            }

            // Clean up JSON markdown code blocks if present
            textResponse = textResponse.Replace("```json", "").Replace("```", "").Trim();

            return AIResponseParser.ParseTailoredResume(textResponse, profile);
        }

        private static string BuildPrompt(CandidateProfile profile, JobPosting job, bool isResume = false)
        {
            return AIPromptBuilder.Build(profile, job, isResume);
        }

        private class ClaudeResponse
        {
            [JsonPropertyName("id")]
            public string? Id { get; set; }

            [JsonPropertyName("type")]
            public string? Type { get; set; }

            [JsonPropertyName("role")]
            public string? Role { get; set; }

            [JsonPropertyName("content")]
            public ClaudeContent[]? Content { get; set; }

            [JsonPropertyName("model")]
            public string? Model { get; set; }

            [JsonPropertyName("stop_reason")]
            public string? StopReason { get; set; }
        }

        private class ClaudeContent
        {
            [JsonPropertyName("type")]
            public string? Type { get; set; }

            [JsonPropertyName("text")]
            public string? Text { get; set; }
        }
    }
}
