namespace WebCV.Infrastructure.Services
{
    public class GroqService(HttpClient httpClient, string apiKey) : IAIService
    {
        private readonly HttpClient _httpClient = httpClient;
        private readonly string _apiKey = apiKey;
        private readonly string ApiUrl = "https://api.groq.com/openai/v1/chat/completions";
        private const string Model = "llama-3.3-70b-versatile"; // Updated from deprecated 3.1 to 3.3

        public async Task<string> GenerateCoverLetterAsync(CandidateProfile profile, JobPosting job)
        {
            var prompt = $"{AISystemPrompts.CoverLetterSystemPrompt}\n\n{BuildPrompt(profile, job)}";
            
            var requestPayload = new
            {
                model = Model,
                messages = new[]
                {
                    new { role = "system", content = AISystemPrompts.CoverLetterSystemPrompt },
                    new { role = "user", content = BuildPrompt(profile, job) }
                },
                temperature = 0.7,
                max_tokens = 4096
            };

            var jsonPayload = JsonSerializer.Serialize(requestPayload);
            var content = new StringContent(jsonPayload, System.Text.Encoding.UTF8, "application/json");

            _httpClient.DefaultRequestHeaders.Clear();
            _httpClient.DefaultRequestHeaders.Add("Authorization", $"Bearer {_apiKey}");

            var response = await _httpClient.PostAsync(ApiUrl, content);

            if (!response.IsSuccessStatusCode)
            {
                var error = await response.Content.ReadAsStringAsync();
                throw new Exception($"Groq API Error: {response.StatusCode} - {error}");
            }

            var responseJson = await response.Content.ReadAsStringAsync();
            var groqResponse = JsonSerializer.Deserialize<GroqResponse>(responseJson);

            return groqResponse?.Choices?[0]?.Message?.Content 
                ?? "Error: No content generated.";
        }

        public async Task<TailoredResumeResult> GenerateTailoredResumeAsync(CandidateProfile profile, JobPosting job)
        {
            var prompt = $"{AISystemPrompts.ResumeTailoringSystemPrompt}\n\n{BuildPrompt(profile, job, isResume: true)}";
            
            var requestPayload = new
            {
                model = Model,
                messages = new[]
                {
                    new { role = "system", content = AISystemPrompts.ResumeTailoringSystemPrompt },
                    new { role = "user", content = BuildPrompt(profile, job, isResume: true) }
                },
                temperature = 0.7,
                max_tokens = 4096
            };

            var jsonPayload = JsonSerializer.Serialize(requestPayload);
            var content = new StringContent(jsonPayload, System.Text.Encoding.UTF8, "application/json");

            _httpClient.DefaultRequestHeaders.Clear();
            _httpClient.DefaultRequestHeaders.Add("Authorization", $"Bearer {_apiKey}");

            var response = await _httpClient.PostAsync(ApiUrl, content);

            if (!response.IsSuccessStatusCode)
            {
                var error = await response.Content.ReadAsStringAsync();
                throw new Exception($"Groq API Error: {response.StatusCode} - {error}");
            }

            var responseJson = await response.Content.ReadAsStringAsync();
            var groqResponse = JsonSerializer.Deserialize<GroqResponse>(responseJson);
            var textResponse = groqResponse?.Choices?[0]?.Message?.Content;

            if (string.IsNullOrEmpty(textResponse))
            {
                throw new Exception("No content generated by Groq.");
            }

            // Clean up JSON markdown code blocks if present
            textResponse = textResponse.Replace("```json", "").Replace("```", "").Trim();

            return AIResponseParser.ParseTailoredResume(textResponse, profile);
        }

        private static string BuildPrompt(CandidateProfile profile, JobPosting job, bool isResume = false)
        {
            return AIPromptBuilder.Build(profile, job, isResume);
        }

        private class GroqResponse
        {
            [JsonPropertyName("id")]
            public string? Id { get; set; }

            [JsonPropertyName("object")]
            public string? Object { get; set; }

            [JsonPropertyName("created")]
            public long Created { get; set; }

            [JsonPropertyName("model")]
            public string? Model { get; set; }

            [JsonPropertyName("choices")]
            public GroqChoice[]? Choices { get; set; }
        }

        private class GroqChoice
        {
            [JsonPropertyName("index")]
            public int Index { get; set; }

            [JsonPropertyName("message")]
            public GroqMessage? Message { get; set; }

            [JsonPropertyName("finish_reason")]
            public string? FinishReason { get; set; }
        }

        private class GroqMessage
        {
            [JsonPropertyName("role")]
            public string? Role { get; set; }

            [JsonPropertyName("content")]
            public string? Content { get; set; }
        }
    }
}
