using WebCV.Domain;
using WebCV.Application.Interfaces;
using WebCV.Application.DTOs;
using Microsoft.Extensions.Logging;

namespace WebCV.Infrastructure.Services;

public class LocalAIService : IAIService
{
    private readonly ILogger<LocalAIService> _logger;

    public LocalAIService(ILogger<LocalAIService> logger)
    {
        _logger = logger;
    }

    public Task<string> GenerateCoverLetterAsync(CandidateProfile profile, JobPosting job)
    {
        // Placeholder implementation – real local inference can be added later.
        _logger.LogInformation("Local AI service invoked for Cover Letter generation.");
        return Task.FromResult("This is a placeholder cover letter generated by the Local AI Service. Real inference implementation is pending.");
    }

    public Task<TailoredResumeResult> GenerateTailoredResumeAsync(CandidateProfile profile, JobPosting job)
    {
        // Placeholder implementation – real local inference can be added later.
        _logger.LogInformation("Local AI service invoked for Tailored Resume generation.");
        
        var placeholderResult = new TailoredResumeResult
        {
             Profile = profile, // Return original profile for now
             DetectedCompanyName = job.CompanyName ?? "Unknown Company",
             DetectedJobTitle = job.Title ?? "Unknown Role"
        };
        return Task.FromResult(placeholderResult);
    }
}
